name: Release

on:
  workflow_dispatch:
    inputs:
      rc:
        type: boolean
        default: false
      version:
        type: string
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install Dependencies
        run: bun install --frozen-lockfile

      - run: bun run build

      - run: bun run prune

      - name: Bump Version
        if: ${{ github.event.inputs.rc }}
        run: bunx changeset version --snapshot rc

      - name: Bump Version
        if: ${{ !github.event.inputs.rc }}
        run: bunx changeset version

      - name: Publish Packages
        if: ${{ github.event.inputs.rc }}
        run: bunx publish --tag rc --no-git-tag

      - name: Publish Packages
        if: ${{ !github.event.inputs.rc }}
        run: bunx public

      - name: Push Changes
        if: ${{ !github.event.inputs.rc }}
        run: git push
